<!--
***************************************************************************************************

										GENERAL FAQs LIST

***************************************************************************************************	
-->
<div class="page" id="helptrouble">	
<div class="mo2f_table_layout">
	<ul class="mo2f_faqs">
			<span class="btn-link"  href=""><li id="cURLfaq">How to enable PHP cURL extension? (Pre-requisite)</li></span>
			<div class="collapse" id="question14">
				<ol>
				<li>Open php.ini.</li>
				<li>Search for extension=php_curl.dll. Uncomment it by removing the semi-colon( ; ) in front of it.</li>
				<li>Restart the Apache Server.</li>
				</ol>
				For any further queries, please submit a query on right hand side in our <b>Support Section</b>.
			</div>
			<hr>
			<span class="btn-link"  href=""><li>I want to enable 2-factor only for administrators ?</li></span>
			<div class="collapse" id="question2">
				2-Factor is enabled by default for administrators on plugin activation. You just need to complete your account setup and configure your mobile from <b>Configure Mobile Tab</b>. Once this is done administrators can login using 2-Factor.
			</div>
			<hr>
			<span class="btn-link"  href=""><li>What happens if an admin tries to login but has not yet registered ?</li></span>
			<div class="collapse" id="question4">
				If an admin has not setup 2-Factor yet, he can still login using his credentials. After logging in, he can go to <b>miniOrange</b> Tab on the top navbar and configure his 2-Factor.
			</div>
			<hr>
			<span class="btn-link"  href=""><li>My users have different types of phones. What phones are supported?</li></span>
			<div class="collapse" id="question5">
				Currently we support smart phones only. If you need 2-Factor for basic phone submit a query in our <b>Support Section</b> on right hand side.
			</div>
			<hr>
			<span class="btn-link"  href=""><li>What if a user does not have a smart phone?</li></span>
			<div class="collapse" id="question6">
				Currently we support smart phone users only. If you need 2-Factor for basic phone users submit a query in our <b>Support Section</b> on right hand side.
			</div>
			<hr>
			<span class="btn-link"  href=""><li>What if I am trying to login from my phone ?</li></span>
			<div class="collapse" id="question15">
				If you are logging in from your phone, just enter the one time passcode from miniOrange Authenticator App.
				Go to Soft Token Tab to see one time passcode.
			</div>
			<hr>
		
		
			<span class="btn-link"  href=""  ><li>My phone has no internet connectivity, how can I login?</li></span>
			<div class="collapse" id="question7">
			   You can login using our alternate login method. <a id="preview1" href="#slider3">Click Here</a> for a preview to see how it works.
			</div>
			<hr>
			<span class="btn-link"  href=""  ><li>My phone is lost, stolen or discharged. How can I login?</li></span>
			<div class="collapse" id="question8">
				You can login using our alternate login method. <a id="preview2" href="#slider4">Click Here</a> for a preview to see how it works.
			</div>
			<hr>
			<span class="btn-link"  href=""  ><li>My phone has no internet connectivity and i am entering the one time passcode from miniOrange Authenticator App, it says Invalid OTP.</li></span>
			<div class="collapse" id="question9">
				Click on the <b>Settings Icon</b> on top right corner in <b>miniOrange Authenticator App</b> and then press <b>Sync button</b> under 'Time correction for codes' to sync your time with miniOrange Servers. If you still can't get it right, submit a query here in our <b>support section</b>.<br><br>
			</div>
			<hr>

			<span class="btn-link"  href=""  ><li>I want to go back to default login with password.</li></span>
			<div class="collapse" id="question12">
				You should go to <b>Login Settings Tab</b> and uncheck <b>Enable 2-Factor for admins</b> 
				and <b>Enable 2-Factor for all others users</b> checkbox. This will disable 2-Factor and you can login using default login form.
			</div>
			<hr>
	
			<span class="btn-link"  href=""><li>I am upgrading my phone.</li></span>
			<div class="collapse" id="question11">
				You should go to <b>Configure Mobile Tab</b> and reconfigure 2-Factor with your new phone. <a id="preview3" href="#slider5">Click Here</a> for a preview to see how it works.
			</div>
			
		<hr>
	
			<span class="btn-link"  href=""  ><li>What If I want to use any other second factor like OTP Over SMS, Security Questions, Device Id, etc ?</li></span>
			<div class="collapse" id="question13">
				miniOrange authentication service has 15+ authentication methods.One time passcodes (OTP) over SMS, OTP over Email, OTP over SMS and Email, Out of Band SMS, Out of Band Email, Soft Token, Push Notification, 
				USB based Hardware token (yubico), Security Questions, Mobile Authentication, Voice Authentication (Biometrics), Phone Verification, Device Identification, Location, Time of Access User Behavior.
				To know more about authentication methods, please visit <a href="http://miniorange.com/strong_auth" target="_blank">http://miniorange.com/strong_auth </a>. If you want to have any other 2-factor for your 
				Magento site, Submit your query here in <b>support section</b>.
			</div>
		
			<hr>
	
		<span class="btn-link" href="">For any other query/problem/request, please feel free to submit a query in our support section on right hand side. We are happy to help you and will get back to you as soon as possible.</span>
		
	</ul>
		<br>		
</div>	
</div>
</div>