<!--
***************************************************************************************************

										HOW IT WORKS

***************************************************************************************************	
-->
<div class="page" id="howitworks">
<div class="mo2f_table_layout">
<h3>HOW IT ALL WORKS?</h3>
	<hr>
	<ul class="mo2f_works">
			<span class="btn-link"  href=""><li id="register-preview" >How to configure Otp Over SMS or Phone Call Verification?</li></span>
			<div class="collapse" id="">
				<div id="slider1">
				  <div  class="control_next" data-slider="1"><img src='<?php echo $this->getImage('arrow') ?>' /></div>
				  <div  class="control_prev" data-slider="1"><img src='<?php echo $this->getImage('arrow') ?>' /></div>	
					<div class="control_info" data-slider="1"></div>									  
				  <ul data-slider="1">
					<li data-pos="1" data-slider="1"><img src='<?php echo $this->getImage('chooseauth') ?>' /></li>		
					<li data-pos="2" data-slider="1"><img src='<?php echo $this->getImage('verifyphone') ?>' /></li>		
					<li data-pos="3" data-slider="1"><img src='<?php echo $this->getImage('validatephone') ?>' /></li>	
				  </ul>  
				</div>
			</div>
			<span class="btn-link"  href=""><li id="register-preview-2" >How to configure Mobile Authentication,Soft Token and Push Notification?</li></span>
			<div class="collapse" id="">
				<div id="slider7">
				  <div  class="control_next" data-slider="7"><img src='<?php echo $this->getImage('arrow') ?>' /></div>
				  <div  class="control_prev" data-slider="7"><img src='<?php echo $this->getImage('arrow') ?>' /></div>	
				<div class="control_info" data-slider="7"></div>									  
				  <ul data-slider="7">
					<li data-pos="1" data-slider="7"><img src='<?php echo $this->getImage('configure') ?>' /></li>		
					<li data-pos="2" data-slider="7"><img src='<?php echo $this->getImage('clickconfiguremobile') ?>' /></li>		
					<li data-pos="3" data-slider="7"><img src='<?php echo $this->getImage('scanqr') ?>' /></li>		
					<li data-pos="4" data-slider="7"><img src='<?php echo $this->getImage('configuremobile') ?>' /></li>		
				  </ul>  
				</div>
			</div>
			<span class="btn-link"  href=""><li id="loginQr-preview">How to Login using Mobile Authentication?</li></span>
			<div class="collapse" id="">
				<div id="slider2">
				  <div  class="control_next" data-slider="2"><img src='<?php echo $this->getImage('arrow') ?>' /></div>
				  <div  class="control_prev" data-slider="2"><img src='<?php echo $this->getImage('arrow') ?>' /></div>	  
				   <div class="control_info" data-slider="2"></div>
				  <ul data-slider="2">
					<li data-pos="1" data-slider="2"><img src='<?php echo $this->getImage('login1') ?>' /></li>					
					<li data-pos="2" data-slider="2"><img src='<?php echo $this->getImage('login2') ?>' /></li>											
					<li data-pos="6" data-slider="2"><img src='<?php echo $this->getImage('login3') ?>' /></li>																					
				  </ul>  
				</div>
			</div>	
			<span class="btn-link"  href=""><li id="offline-preview" >How to Login when your phone is offline?</li></span>
			<div class="collapse" id="">
				<div id="slider3">
				  <div  class="control_next" data-slider="3"><img src='<?php echo $this->getImage('arrow') ?>' /></div>
				  <div  class="control_prev" data-slider="3"><img src='<?php echo $this->getImage('arrow') ?>' /></div>	  
				  <div class="control_info" data-slider="3"></div>
				  <ul data-slider="3">
					<li data-pos="1" data-slider="3"><img src='<?php echo $this->getImage('login1') ?>' /></li>					
					<li data-pos="2" data-slider="3"><img src='<?php echo $this->getImage('phone-offline') ?>' /></li>					
					<li data-pos="4" data-slider="3"><img src='<?php echo $this->getImage('softtoken') ?>' /></li>		
				  </ul>  
				</div>
			</div>
			<span class="btn-link"  href=""><li id="phonelost-preview">How to Login when your phone is unavailable?</li></span>
			<div class="collapse" id="">
				<div id="slider4">
				  <div class="control_next"  data-slider="4"><img src='<?php echo $this->getImage('arrow') ?>' /></div>
				  <div class="control_prev"  data-slider="4"><img src='<?php echo $this->getImage('arrow') ?>' /></div>	  
				  <div class="control_info"  data-slider="4"></div>
				  <ul data-slider="4">
					<li data-pos="1" data-slider="4"><img  src='<?php echo $this->getImage('login1') ?>' /></li>					
					<li data-pos="2" data-slider="4"><img  src='<?php echo $this->getImage('forgot-phone') ?>' /></li>					
					<li data-pos="3" data-slider="4"><img  src='<?php echo $this->getImage('sendingotp') ?>' /></li>					
					<li data-pos="5" data-slider="4"><img  src='<?php echo $this->getImage('forgotphone') ?>' /></li>
				  </ul>  
				</div>
			</div>	
			<span class="btn-link"  href=""><li id="reconfigure-preview">How to ReConfigure your Mobile?</li></span>
			<div class="collapse" id="">
				<div id="slider5">
				  <div  class="control_next" data-slider="5"><img src='<?php echo $this->getImage('arrow') ?>' /></div>
				  <div  class="control_prev" data-slider="5"><img src='<?php echo $this->getImage('arrow') ?>' /></div>	
					<div class="control_info" data-slider="5"></div>									  
				  <ul data-slider="5">
					<li data-pos="1" data-slider="5"><img  src='<?php echo $this->getImage('clickconfiguremobile2') ?>' /></li>
					<li data-pos="4" data-slider="5"><img  src='<?php echo $this->getImage('reconfiguremobile') ?>' /></li>
					<li data-pos="5" data-slider="5"><img  src='<?php echo $this->getImage('configuremobile') ?>' /></li>				
				  </ul>  
				</div>
			</div>	
			<span class="btn-link"  href=""><li id="reconfigure-preview-2">How to Change your Number for OTP over SMS and Phone Call verification?</li></span>
			<div class="collapse" id="">
				<div id="slider8">
				  <div  class="control_next" data-slider="8"><img src='<?php echo $this->getImage('arrow') ?>' /></div>
				  <div  class="control_prev" data-slider="8"><img src='<?php echo $this->getImage('arrow') ?>' /></div>	
					<div class="control_info" data-slider="8"></div>									  
				  <ul data-slider="8">
					<li data-pos="1" data-slider="8"><img  src='<?php echo $this->getImage('reconfigurephone') ?>' /></li>
					<li data-pos="2" data-slider="8"><img src='<?php echo $this->getImage('verifyphone') ?>' /></li>		
					<li data-pos="3" data-slider="8"><img src='<?php echo $this->getImage('validatephone') ?>' /></li>		
				  </ul>  
				</div>
			</div>	
			<span class="btn-link"  href=""><li id="cache-preview">How to flush Magento Cache?</li></span>
			<div class="collapse" id="">
				<div id="slider6">
				  <div  class="control_next" data-slider="6"><img src='<?php echo $this->getImage('arrow') ?>' /></div>
				  <div  class="control_prev" data-slider="6"><img src='<?php echo $this->getImage('arrow') ?>' /></div>	 
				   <div class="control_info" data-slider="6"></div>									  
				  <ul data-slider="6">
					<li data-pos="1" data-slider="6"><img src='<?php echo $this->getImage('cachesetting') ?>' /></li>
					<li data-pos="2" data-slider="6"><img src='<?php echo $this->getImage('savecache') ?>' /></li>
				  </ul>  
				</div>
			</div>	
			
	</ul>		
			
	
</div>
</div>