	<html>
	<head>		
		<link href="https://auth.miniorange.com/moas/css/telephone.css" rel="stylesheet">
		<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN).'adminhtml/default/default/css/MiniOrange_2factor/adminSettings.css'; ?>"></link>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
		<script src="https://auth.miniorange.com/moas/js/intlTelInput.min.js"></script>
		<!-- SETTINGS PAGE SCRIPT -->
		<script>
			var $m = jQuery.noConflict();
			$m(document).ready(function() {
				$email = "<?php echo $this->getConfig('email'); ?>";
			    $downloaded = "<?php echo $this->getConfig('downloaded'); ?>";
			    $twofactortype = "<?php echo $this->getConfig('twofactortype'); ?>"
			    $showloginsettings = "<?php echo Mage::getSingleton('admin/session')->getshowLoginSettings(); ?>";
			    $showTwoFactorSettings = "<?php echo Mage::getSingleton('admin/session')->getShowTwoFactorSettings(); ?>";
			});	
		</script>
		<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN).'adminhtml/default/default/js/MiniOrange_2factor/adminSettings.js'; ?>"></script>
		<!-- POLLING SCRIPT -->
		<script>
			var transId = "<?php echo $this->getTransactionId(); ?>";
			var test = "<?php echo Mage::getSingleton('admin/session')->getTestValidationScreen(); ?>";
			var testMobile = "<?php echo Mage::getSingleton('admin/session')->getShowTestMobileAuth(); ?>";
			if (test == "1") {
		        var postUrl = "<?php echo $this->getHostURl()  ?>" + "/moas/api/auth/auth-status";
		    } else {
		        var postUrl = "<?php echo $this->getHostURl()  ?>" + "/moas/api/auth/registration-status";
		    }
		    var url1 = "<div id='success' style='margin-left: 1%; margin-top:2%;'><img src='" + "<?php echo $this->getImage('right') ?>" + "' /></div>";
		    var url2 = "<div id='error' style='margin-left: 1%; margin-top:2%;'><img src='" + "<?php echo $this->getImage('wrong') ?>" + "' /></div>";
		</script>
		<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN).'adminhtml/default/default/js/MiniOrange_2factor/adminSettingsPolling.js'; ?>"></script>
		<!-- SLIDER SCRIPT -->
		<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN).'adminhtml/default/default/js/MiniOrange_2factor/sliderScript.js'; ?>"></script>
	</head>		
	<body>
		<?php 
			$user = Mage::getSingleton('admin/session')->getUser();
			$roleName = $user->getRole()->getRoleName();
			$roleID = $user->getRole()->getRoleId();
			$access = (strcmp($roleName,"Administrators")==0 || strcmp($roleName,"Super Administrator")==0) ? '1' : $this->twofactorEnabledForRole($roleID);
			if( !$access ){?>
			<h1 class="page-heading">Access denied</h1>
			<p>Please try to logout and sign in again.<br>
			If this message persists, please contact the store owner.</p>
		<?php }else{ ?>
		<div class="heading"> <h3>MINIORANGE TWO FACTOR EXTENSION CONFIGURATION</h3></div>
		<div class="mo2f_container">
		<div class="container">
		  <ul class="navbar navbar-tabs">
			<?php if( $this->getConfig('email')){ ?>
			<li id="user_profile"><a data-method="#userprofile">User Profile</a></li>
			<?php }else{?>
			<li id="account_setup"><a data-method="#accountsetup">Account Setup</a></li>
			<?php }?>
			<li id="two_factor_setup"><a data-method="#twofactorsetup">Two Factor Setup</a></li>
			<li id="login_settings"><a data-method="#loginsettings">Login Settings</a></li>
			<li id="licencing_plans"><a data-method="#licencingplans">Licencing Plans</a></li>
			<li id="how_it_works"><a data-method="#howitworks">How it Works</a></li>
			<li id="help_trouble"><a data-method="#helptrouble">FAQs</a></li>
		  </ul>
		<div class="container-page">
			<div id="messages">
				<ul class="mini-messages">
				<?php if(Mage::getSingleton('core/session')->getErrorMessage()){?>
				<li class="error-msg"><ul><li><span><?php echo Mage::getSingleton('core/session')->getErrorMessage(); ?></span><a id="error-cancel" href="#">&times;</a></li></ul></li>
				<?php }?>
				<?php if(Mage::getSingleton('core/session')->getSuccessMessage()){?>
				<li class="success-msg"><ul><li><span><?php echo Mage::getSingleton('core/session')->getSuccessMessage(); ?></span><a id="success-cancel" href="#">&times;</a></li></ul></li>
				<?php }?>
				</ul>						
			</div>
			<!-- USER PROFILE TAB -->
			<?php if( $this->getConfig('email') ){ ?>
				<div class="page" id="userprofile">
				<div class="mo2f_table_layout">
				<div><h3>YOUR PROFILE INFORMATION</h3><hr></div>	
					<table>
					  <tr>
						<td><b>miniOrange Account Email</b></td>
						<td><?php echo $this->getConfig('email')?></td> 
					  </tr>
					  <tr>
						<td><b>Customer Key</b></td>
						<td><?php echo $this->getConfig('customerKey')?></td> 
					  </tr>
					  <tr>
						<td><b>Api Key</b></td>
						<td><?php echo $this->getConfig('apiKey')?></td> 
					  </tr>
					  <tr>
						<td><b>Api Token</b></td>
						<td><?php echo $this->getConfig('apiToken')?></td> 
					  </tr>
					</table>
					</div>
				</div>
			<?php }else{
				#### ACCOUNT SETUP TAB ####
				echo $this->getLayout()->createBlock('MiniOrange_2factor/mo2fConfig')->setTemplate('miniorange_2factor/accountSetup.phtml')->toHtml(); 
			}?>
			
			<!-- TWO FACTOR SETUP -->
			<div class="page" id="twofactorsetup">
			<div id="twofactorpage">
			<?php if(!Mage::getSingleton('admin/session')->getShowConfigureMobile() && !Mage::getSingleton('admin/session')->getShowPhoneValidation() 
						&& !Mage::getSingleton('admin/session')->getShowQR() && !Mage::getSingleton('admin/session')->getTestValidationScreen() 
					&& !Mage::getSingleton('admin/session')->getShowGoogleAuthSetup() && !Mage::getSingleton('admin/session')->getShowKBASetup()) { ?>
			
				<!-- TWO FACTOR LIST -->
				<?php echo $this->getLayout()->createBlock('MiniOrange_2factor/mo2fConfig')->setTemplate('miniorange_2factor/twoFactorList.phtml')->toHtml(); ?>

				<form name="f" method="post" action="<?php echo $this->getadminurl('*/*/showQRCode') ?>" id="mo2f_2factor_reconfigure_mobile_form">
					<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
					<input type="hidden" id="reconfigure_mobile" name="reconfigure_mobile" value="" />
				</form>
				<form name="f" method="post" action="<?php echo $this->getadminurl('*/*/reconfigurePhone') ?>" id="mo2f_2factor_reconfigure_phone_form">
					<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
					<input type="hidden" id="phone_reconfigure" name="phone_reconfigure" value="" />
				</form>
				<form name="f" method="post" action="<?php echo $this->getadminurl('*/*/reconfigureGA') ?>" id="mo2f_2factor_reconfigure_ga_form">
					<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
				</form>
				<form name="f" method="post" action="<?php echo $this->getadminurl('*/*/reconfigureKBA') ?>" id="mo2f_2factor_reconfigure_kba_form">
					<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
				</form>
				<form name="f" method="post" action="<?php echo $this->getadminurl('*/*/testTwoFactor') ?>" id="mo2f_2factor_test_form">
					<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
					<input type="hidden" id="test_2factor" name="test_2factor" value="">
				</form>	
			<?php }?>
			
			<?php if(Mage::getSingleton('admin/session')->getTestValidationScreen()){ ?>
				<!-- TEST MOBILE TWO FACTOR -->
				<?php echo $this->getLayout()->createBlock('MiniOrange_2factor/mo2fConfig')->setTemplate('miniorange_2factor/testMobileTwoFactor.phtml')->toHtml(); ?>
			<?php }?>
			
			<?php if(Mage::getSingleton('admin/session')->getShowConfigureMobile() || Mage::getSingleton('admin/session')->getShowQR()){?>
				<!-- CONFIGURE MOBILE SETUP -->
				<?php echo $this->getLayout()->createBlock('MiniOrange_2factor/mo2fConfig')->setTemplate('miniorange_2factor/configureMobile.phtml')->toHtml(); ?>
			<?php }?>

			<form name="f" method="post" id="mobile_register_form" action="<?php echo $this->getadminurl('*/*/transactionSuccess') ?>">
				<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
			</form>
			<form name="f" method="post" id="mobile_register_failed" action="<?php echo $this->getadminurl('*/*/transactionTimeOut') ?>">
				<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
			</form>
					
			<?php if(Mage::getSingleton('admin/session')->getShowPhoneValidation()){ ?>
				<!-- TEST PHONE TWO FACTOR -->
				<?php echo $this->getLayout()->createBlock('MiniOrange_2factor/mo2fConfig')->setTemplate('miniorange_2factor/testPhoneTwoFactor.phtml')->toHtml(); ?>
			<?php }?>
	
			<?php if(Mage::getSingleton('admin/session')->getShowGoogleAuthSetup()){ ?>
				<!-- GOOGLE AUTHENTICATOR SETUP -->
				<?php echo $this->getLayout()->createBlock('MiniOrange_2factor/mo2fConfig')->setTemplate('miniorange_2factor/googleAuthenticatorSetup.phtml')->toHtml(); ?>
			<?php }?>
			
			<?php if(Mage::getSingleton('admin/session')->getShowKBASetup()){ ?>
				<!-- KBA SETUP -->
				<?php echo $this->getLayout()->createBlock('MiniOrange_2factor/mo2fConfig')->setTemplate('miniorange_2factor/kbaSetup.phtml')->toHtml(); ?>
			<?php }?>
			</div>
			<div id="twofactorselect" >
				<center><div style="font-weight:bold;font-size:18px;margin-top:5%;">PROCESSING YOUR REQUEST. PLEASE WAIT!</div></center>
				<span  id="progress_bar"></span>
			</div>
			</div>
			
			<!-- LOGIN SETTINGS TAB -->
			<?php echo $this->getLayout()->createBlock('MiniOrange_2factor/mo2fConfig')->setTemplate('miniorange_2factor/loginSettings.phtml')->toHtml(); ?>

			<!-- LICENSING TAB -->
			<?php echo $this->getLayout()->createBlock('MiniOrange_2factor/mo2fConfig')->setTemplate('miniorange_2factor/showPricing.phtml')->toHtml(); ?>
					
			<!-- HOW IT WORKS TAB -->
			<?php echo $this->getLayout()->createBlock('MiniOrange_2factor/mo2fConfig')->setTemplate('miniorange_2factor/mo2fFaqs.phtml')->toHtml(); ?>
				
			<!-- HELP AND TROUBLESHOOTING TAB -->
			<?php echo $this->getLayout()->createBlock('MiniOrange_2factor/mo2fConfig')->setTemplate('miniorange_2factor/generalFaqs.phtml')->toHtml(); ?>
		</div>
			
		<!-- SUPPORT TAB -->
		<div id="minisupport">
		 <ul class="navbar navbar-tabs">
			<li id="mini_support" class="always-active"><a href="#minisupport" class="mini_support">Support</a></li>
			</ul>
				<div class="mo2f_support_layout">
					<h3>SUPPORT</h3>
					<hr>
					<form name="f" method="post" action="<?php echo $this->getadminurl('*/*/supportSubmit') ?>">
						<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
						<div><b>Need any help? Just send us a query so we can help you.</b><br /><br/></div>
						<div>
							<table>
								<tr><td>
									<input type="email" class="mo2f_table_textbox" id="query_email" name="query_email" value="<?php echo Mage::getSingleton('admin/session')->getUser()->getEmail() ?>" placeholder="Enter your email" required="true" />
									</td>
								</tr>
								<tr><td>
									<input type="text" class="mo2f_table_textbox" name="query_phone" id="query_phone" title="Phone with country code eg. +1xxxxxxxxxx" placeholder="Phone with country code eg. +1xxxxxxxxxx" value="<?php echo $this->getConfig('phone')?>" pattern="[\+]?[0-9]{1,4}\s?[0-9]{10}"/>
									</td>
								</tr>
								<tr>
									<td>
										<textarea id="query" name="query" style="resize:vertical;height:143px;" onkeyup="mo2f_valid(this)" onblur="mo2f_valid(this)" onkeypress="mo2f_valid(this)" placeholder="Write your query here"></textarea>
									</td>
								</tr>
							</table>
						</div>
						<div class="button-align">
							<input type="submit" name="send_query" id="send_query" value="Submit Query" style="margin-bottom:3%;" class="button button-primary button-large" />
						</div>
					</form>
					<br />			
				</div>
				<br>
			</div>
		</div>
		
		<form style="display:none;" id="mo2fa_loginform" action="https://auth.miniorange.com/moas/login" target="_blank" method="post">
			<input type="email" name="username" value="<?php echo $this->getConfig('email')?>" />
			<input type="text" name="redirectUrl" value="https://auth.miniorange.com/moas/initializepayment" />
			<input type="text" name="requestOrigin" id="requestOrigin"  />
		</form>
		
		<script>
			function mo2f_upgradeform(planType){
				$j('#requestOrigin').val(planType);
				$j('#mo2fa_loginform').submit();
			}
		</script>
		
		
		<?php }?>
	</body>
	</html>