<!--
***************************************************************************************************

										PRICING LIST

***************************************************************************************************	
-->
<div class="page" id="licencingplans">
<input type="submit" name="submit" value="OK, Got It" style="width:100px;float:right;margin-right:2%" class="button button-primary button-large" onclick="jQuery('#two_factor_setup > a').click();">
<h3>LICENSING PLANS</h3><br/>
<hr>
<div class="mo2f_table_layout">
	<table class="mo2f_pricing_table">		
		<tbody><tr style="vertical-align:top;">
			<td>
				<div class="mo2f_thumbnail mo2f_pricing_free_tab">
					<div style="height:13%;">
						<h2 class="mo2f_pricing_header">Free</h2>
						<h3>( You are automatically on this plan )</h3>	
					</div>
					<hr>
					<div style="padding:2% 0;">
						<span class="mo2f_pricing_text">For 1 user - Forever</span>
					</div>
					<hr>
					<div style="height:4%;padding:2% 0;">
						<span class="mo2f_pricing_text" style="margin-bottom:59px;">$0 - Subscription Fees</span>
					</div>
					<hr>
					<div style="height:39%;padding:2% 0;">
						<span class="mo2f_pricing_text">Features:<br/><br/></span>
						<span class="mo2f_pricing_text">
							Limited Authentication Methods<br>
							Remember Device
						</span>
					</div>
					<hr>
					<div style="height:15%;padding:2% 0;">
						<span class="mo2f_pricing_text">
							Backup Method:<br/><br/>
							Security Questions (KBA)
						</span>
					</div>
					<hr>
					<div style="padding:2% 0;">
						<span class="mo2f_pricing_text">Basic Support by Email</span>
					</div>
				</div>
			</td>
			<td>
				<div class="mo2f_thumbnail mo2f_pricing_paid_tab">
					<div style="height:13%;">
						<h3 class="mo2f_pricing_header" style="margin-bottom: 12px;">Do it yourself</h3>
						<input type="submit" class="button button-primary button-large" value="Click here to upgrade" onclick="mo2f_upgradeform('magento_2fa_basic_plan')"/><span class="mo2f_pricing_sub_header">*</span>
					</div>
					<hr>
					<div style="padding:2% 0;">
						<span class="mo2f_pricing_text">For 1+ user</span>
					</div>
					<hr>
					<div style="height:4%;padding:2% 0;">
						<span class="mo2f_pricing_text" style="margin-bottom:59px;">$6 / user / year - Subscription Fees **</span>
					</div>
					<hr>
					<div style="height:39%;padding:2% 0;">
						<span class="mo2f_pricing_text">Features:<br/><br/></span>
						<span class="mo2f_pricing_text">
							All Authentication Methods<br>
							Remember Device<br>
							Enforce 2FA registration for users<br>
							Manage Registered Device Profiles<br>
							Custom Redirection<br>
							Customize Email Templates<br>
							Customize SMS Templates<br>
							Customize Powered By logo
						</span>
					</div>
					<hr>
					<div style="height:15%;padding:2% 0;">
						<span class="mo2f_pricing_text">
							Backup Method:<br/><br/>
							Security Questions (KBA)<br>
							OTP over EMAIL</span>
					</div>
					<hr>
					<div style="padding:2% 0;">
						<span class="mo2f_pricing_text">Basic Support By Email</span>
					</div>
				</div>
			</td>
			<td>
				<div class="mo2f_thumbnail mo2f_pricing_free_tab">
					<div style="height:13%;">
						<h3 class="mo2f_pricing_header" style="margin-bottom: 12px;">Premium</h3>
						<input type="submit" class="button button-primary button-large" value="Click here to upgrade" onclick="mo2f_upgradeform('magento_2fa_premium_plan')"/><span class="mo2f_pricing_sub_header">*</span>
					</div>
					<hr>
					<div style="padding:2% 0;">
						<span class="mo2f_pricing_text">For 1+ user, Setup and Custom Work</span>
					</div>
					<hr>
					<div style="height:4%;padding:2% 0;">
						<span class="mo2f_pricing_text">$6 / user / year - Subscription Fees **
					</div>
					<hr>
					<div style="height:39%;padding:2% 0;">
						<span class="mo2f_pricing_text">Features:<br/><br/></span>
						<span class="mo2f_pricing_text">
							All Authentication Methods<br>
							Remember Device<br>
							Enforce 2FA registration for users<br>
							Manage Registered Device Profiles<br>
							Custom Redirection<br>
							Customize Email Templates<br>
							Customize SMS Templates<br>
							Customize Powered By logo<br>
							End to End 2FA Integration***
						</span>
					</div>
					<hr>
					<div style="height:15%;padding:2% 0;">
						<span class="mo2f_pricing_text">
							Backup Method:<br/><br/>
							Security Questions (KBA)<br>
							OTP over EMAIL</span>
					</div>
					<hr>
					<div style="padding:2% 0;">
						<span class="mo2f_pricing_text">Premium Support Plans Available</span>
					</div>
				</div>
			</td>
		</tr>
		</tbody>
	</table>
	<div style="margin:0 0 2% 2%;">
		<h3>* Steps to upgrade to premium plugin -</h3>
		<p>1. You will be redirected to miniOrange Login Console. Enter your password with which you created an account with us and verify your 2nd factor. After that you will be redirected to payment page.</p>
		<p>2. Enter you card details and complete the payment. On successful payment completion, you will see the link to download the premium plugin.</p>
		<p>3. Once you download the premium plugin, just unzip it and replace the folder with existing plugin. </p>
		<b>Note: Do not delete the plugin from the Magento Admin Panel and upload the plugin using zip. Your saved settings will get lost.</b>
	
		<h3>** Volume discounts are available. Contact Us for details if you have more than 100 users.</h3>
		<p>You can mail us at <a href="mailto:info@miniorange.com"><b>info@miniorange.com</b></a> or submit the support form under User Profile tab to contact us.</p>
		<h3>*** End to End 2FA Integration - We will setup a Conference Call / Gotomeeting and do end to end setup for you. We provide services to do the setup on your behalf.
	</div>
</div>
</div>