<!--
***************************************************************************************************

										GENERAL FAQs

***************************************************************************************************	
-->
<div class="mo_page" id="helptrouble">	
	<div class="mo2f_table_layout">
		<ul class="mo2f_faqs">
				<a class="btn-link"  href=""><li>What phones are supported?</li></a>
				<div class="collapse" id="question5">
					Currently we support smart phones only. If you need 2-Factor for basic phone submit a query in our <b>Support Section</b> on right hand side.
				</div>
				<hr>
				<a class="btn-link"  href=""><li>What if i dont have a smart phone?</li></a>
				<div class="collapse" id="question6">
					Currently we support smart phone users only. If you need 2-Factor for basic phone users submit a query in our <b>Support Section</b> on right hand side.
				</div>
				<hr>
				<a class="btn-link"  href=""><li>What if I am trying to login from my phone ?</li></a>
				<div class="collapse" id="question15">
					If you are logging in from your phone, just enter the one time passcode from miniOrange Authenticator App.
					Go to Soft Token Tab to see one time passcode.
				</div>
				<hr>
				<a class="btn-link"  href=""><li>My phone has no internet connectivity, how can I login?</li></a>
				<div class="collapse" id="question7">
				   You can login using our alternate login method. <a id="preview1" href="#slider3">Click Here</a> for a preview to see how it works.
				</div>
				<hr>
				<a class="btn-link"  href=""><li>My phone is lost, stolen or discharged. How can I login?</li></a>
				<div class="collapse" id="question8">
					You can login using our alternate login method. <a id="preview2" href="#slider4">Click Here</a> for a preview to see how it works.
				</div>
				<hr>
				<a class="btn-link"  href=""><li>My phone has no internet connectivity and i am entering the one time passcode from miniOrange Authenticator App, it says Invalid OTP.</li></a>
				<div class="collapse" id="question9">
					Click on the <b>Settings Icon</b> on top right corner in <b>miniOrange Authenticator App</b> and then press <b>Sync button</b> under 'Time correction for codes' to sync your time with miniOrange Servers. If you still can't get it right, submit a query here in our <b>support section</b>.<br><br>
				</div>
				<hr>
				<a class="btn-link"  href=""><li>I am upgrading my phone.</li></a>
				<div class="collapse" id="question11">
					You should go to <b>Configure Mobile Tab</b> and reconfigure 2-Factor with your new phone. <a id="preview3" href="#slider5">Click Here</a> for a preview to see how it works.
				</div>	
				<hr>
				<a class="btn-link"  href=""  ><li>What If I want to use any other second factor like OTP Over SMS, Security Questions, Device Id, etc ?</li></a>
				<div class="collapse" id="question13">
					miniOrange authentication service has 15+ authentication methods.One time passcodes (OTP) over SMS, OTP over Email, OTP over SMS and Email, Out of Band SMS, Out of Band Email, Soft Token, Push Notification, 
					USB based Hardware token (yubico), Security Questions, Mobile Authentication, Voice Authentication (Biometrics), Phone Verification, Device Identification, Location, Time of Access User Behavior.
					To know more about authentication methods, please visit <a href="http://miniorange.com/strong_auth" target="_blank">http://miniorange.com/strong_auth </a>. If you want to have any other 2-factor for your 
					Magento site, Submit your query here in <b>support section</b>.
				</div>
				<hr>
		</ul>
					
	</div>	
</div>
</div>
</div>