<!--
***************************************************************************************************

										HOW IT WORKS

***************************************************************************************************	
-->
<div class="mo_page" id="howitworks">
	<div class="mo2f_table_layout">
	<h3>HOW IT ALL WORKS?</h3>
		<hr>
		<ul class="mo2f_works">
				<a class="btn-link"  href=""><li id="register-preview" >How to configure Otp Over SMS or Phone Call Verification?</li></a>
				<div class="collapse" id="">
					<div id="slider1">
					  <div  class="control_next" data-slider="1"><img src='<?php echo $this->getImage('arrow') ?>' /></div>
					  <div  class="control_prev" data-slider="1"><img src='<?php echo $this->getImage('arrow') ?>' /></div>	  
					  <div class="control_info" data-slider="1"></div>
					  <ul data-slider="1">
						<li data-pos="1" data-slider="1"><img  src='<?php echo $this->getImage('frontend_chooseauth') ?>' /></li>
						<li data-pos="2" data-slider="1"><img  src='<?php echo $this->getImage('frontend_verifyphone') ?>' /></li>
						<li data-pos="3" data-slider="1"><img  src='<?php echo $this->getImage('frontend_validatephone') ?>' /></li>
					  </ul>  
					</div>
				</div>
				<a class="btn-link"  href=""><li id="register-preview-2" >How to configure Mobile Authentication,Soft Token and Push Notification?</li></a>
				<div class="collapse" id="">
					<div id="slider6">
					  <div  class="control_next" data-slider="6"><img src='<?php echo $this->getImage('arrow') ?>' /></div>
					  <div  class="control_prev" data-slider="6"><img src='<?php echo $this->getImage('arrow') ?>' /></div>	  
					  <div class="control_info" data-slider="6"></div>
					  <ul data-slider="6">
						<li data-pos="1" data-slider="6"><img  src='<?php echo $this->getImage('frontend_configure') ?>' /></li>
						<li data-pos="2" data-slider="6"><img  src='<?php echo $this->getImage('frontend_downloadapp') ?>' /></li>
						<li data-pos="3" data-slider="6"><img  src='<?php echo $this->getImage('frontend_configureaccount') ?>' /></li>
						<li data-pos="4" data-slider="6"><img  src='<?php echo $this->getImage('frontend_mobilevalid') ?>' /></li>
					  </ul>  
					</div>
				</div>
				<a class="btn-link"  href=""><li id="loginQr-preview">How to Login using Mobile Authentication?</li></a>
				<div class="collapse" id="">
					<div id="slider2">
					  <div  class="control_next" data-slider="2" ><img src='<?php echo $this->getImage('arrow') ?>' /></div>
					  <div  class="control_prev" data-slider="2"><img src='<?php echo $this->getImage('arrow') ?>' /></div>	
						<div class="control_info" data-slider="2"></div>									  
					  <ul data-slider="2">
						<li data-pos="1" data-slider="2"><img  src='<?php echo $this->getImage('frontend_login1') ?>' /></li>					
						<li data-pos="2" data-slider="2"><img  src='<?php echo $this->getImage('frontend_mobile') ?>' /></li>					
						<li data-pos="3" data-slider="2"><img  src='<?php echo $this->getImage('frontend_mobile2') ?>' /></li>										
					  </ul>  
					</div>
				</div>	
				<a class="btn-link"  href=""><li id="offline-preview" >How to Login when your phone is offline?</li></a>
				<div class="collapse" id="">
					<div id="slider3">
					  <div  class="control_next" data-slider="3"><img src='<?php echo $this->getImage('arrow') ?>' /></div>
					  <div  class="control_prev" data-slider="3"><img src='<?php echo $this->getImage('arrow') ?>' /></div>	  
					  <div class="control_info" data-slider="3"></div>
					  <ul data-slider="3">
						<li data-pos="1" data-slider="3"><img  src='<?php echo $this->getImage('frontend_login1') ?>' /></li>					
						<li data-pos="2" data-slider="3"><img  src='<?php echo $this->getImage('frontend_phoneoffline') ?>' /></li>					
						<li data-pos="3" data-slider="3"><img  src='<?php echo $this->getImage('frontend_softtoken') ?>' /></li>	
					  </ul>  
					</div>
				</div>
				<a class="btn-link"  href=""><li id="phonelost-preview">How to Login when your phone is unavailable?</li></a>
				<div class="collapse" id="">
					<div id="slider4">
					  <div  class="control_next" data-slider="4"><img src='<?php echo $this->getImage('arrow') ?>' /></div>
					  <div  class="control_prev" data-slider="4"><img src='<?php echo $this->getImage('arrow') ?>' /></div>	
						<div class="control_info" data-slider="4"></div>											  
					  <ul data-slider="4">
						<li data-pos="1" data-slider="4"><img  src='<?php echo $this->getImage('frontend_login1') ?>' /></li>					
						<li data-pos="2" data-slider="4"><img  src='<?php echo $this->getImage('frontend_forgotphonelink') ?>' /></li>					
						<li data-pos="3" data-slider="4"><img  src='<?php echo $this->getImage('frontend_forgotphone') ?>' /></li>					
						<li data-pos="4" data-slider="4"><img  src='<?php echo $this->getImage('frontend_forgotphone2') ?>' /></li>	
					  </ul>  
					</div>
				</div>	
				<a class="btn-link"  href=""><li id="reconfigure-preview">How to ReConfigure your Mobile?</li></a>
				<div class="collapse" id="">
					<div id="slider5">
					  <div  class="control_next" data-slider="5"><img src='<?php echo $this->getImage('arrow') ?>' /></div>
					  <div  class="control_prev" data-slider="5"><img src='<?php echo $this->getImage('arrow') ?>' /></div>	  
						<div class="control_info" data-slider="5"></div>
					  <ul data-slider="5">
						<li data-pos="1" data-slider="5"><img  src='<?php echo $this->getImage('frontend_reconfiguremobile') ?>' /></li>
						<li data-pos="2" data-slider="5"><img  src='<?php echo $this->getImage('frontend_reconfigure') ?>' /></li>
						<li data-pos="3" data-slider="5"><img  src='<?php echo $this->getImage('frontend_mobilevalid') ?>' /></li>
					  </ul>  
					</div>
				</div>	
				<a class="btn-link"  href=""><li id="reconfigure-preview-2">How to Change your Number for OTP over SMS and Phone Call verification?</li></a>
				<div class="collapse" id="">
					<div id="slider7">
					  <div  class="control_next" data-slider="7"><img src='<?php echo $this->getImage('arrow') ?>' /></div>
					  <div  class="control_prev" data-slider="7"><img src='<?php echo $this->getImage('arrow') ?>' /></div>	  
						<div class="control_info" data-slider="7"></div>
					  <ul data-slider="7">
						<li data-pos="1" data-slider="7"><img  src='<?php echo $this->getImage('frontend_reconfigurephone') ?>' /></li>
						<li data-pos="2" data-slider="7"><img  src='<?php echo $this->getImage('frontend_verifyphone') ?>' /></li>
						<li data-pos="3" data-slider="7"><img  src='<?php echo $this->getImage('frontend_validatephone') ?>' /></li>
					  </ul>  
					</div>
				</div>
			</ul>		
	</div>
</div>